#!/bin/bash
#SBATCH -A TG-CCR140008
#SBATCH -J gpu
#SBATCH -o gpu.stdout
#SBATCH -n 1
#SBATCH -p gpudev
#SBATCH -t 00:30:00

ibrun ./gpu -N 10
ibrun ./gpu -N 20
ibrun ./gpu -N 50
ibrun ./gpu -N 100
ibrun ./gpu -N 200
