#!/bin/bash
#SBATCH -A TG-CCR140008
#SBATCH -J gpu
#SBATCH -o gpu.stdout
#SBATCH -n 1
#SBATCH -p gpudev
#SBATCH -t 00:30:00

ibrun ./gpu -n 10
ibrun ./gpu -n 20
ibrun ./gpu -n 50
ibrun ./gpu -n 100
ibrun ./gpu -n 200


